# Generated by Django 4.0.1 on 2022-03-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_alter_donors_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='user',
        ),
    ]
