# Generated by Django 4.0.1 on 2022-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
