# Generated by Django 4.0.1 on 2022-04-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donors_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiaries/profile_pictures/'),
        ),
    ]
