# Generated by Django 4.0.1 on 2022-03-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='donations',
            options={'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='pickupstations',
            options={'verbose_name_plural': 'Pickup Stations'},
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='delivery_faiiled',
            new_name='delivery_failed',
        ),
        migrations.AddField(
            model_name='donations',
            name='donatio_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pickupstations',
            name='doations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiaries.donations'),
        ),
    ]
