# Generated by Django 4.0.1 on 2022-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_options_alter_donations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
