# Generated by Django 4.0.1 on 2022-03-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donors_email_confirmed'),
        ('project_managers', '0003_projectmanager_email_confirmed'),
        ('beneficiaries', '0003_beneficiary_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donors.donors'),
        ),
        migrations.AddField(
            model_name='donations',
            name='project_managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_managers.projectmanager'),
        ),
    ]
