# Generated by Django 4.0.1 on 2022-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_donations_donor_donations_project_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='beneficiaries/poster/'),
        ),
    ]
