# Generated by Django 4.0.1 on 2022-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0005_donations_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
