# Generated by Django 4.0.1 on 2022-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_alter_ngoprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
