# Generated by Django 4.0.1 on 2022-03-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0003_ngoprofile_email_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='first_name',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='last_name',
            new_name='headquarters',
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='name',
            field=models.CharField(default='kk', max_length=100),
            preserve_default=False,
        ),
    ]
