# Generated by Django 4.0.1 on 2022-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0004_rename_first_name_ngoprofile_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='first_name',
            field=models.CharField(default='kk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='last_name',
            field=models.CharField(default='u', max_length=100),
            preserve_default=False,
        ),
    ]
