# Generated by Django 4.0.1 on 2022-03-15 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_managers', '0003_projectmanager_email_confirmed'),
        ('donors', '0005_donors_email_confirmed'),
        ('NGO', '0005_ngoprofile_first_name_ngoprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOdonations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('donation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='beneficiaries/poster/')),
                ('donatio_description', models.CharField(blank=True, max_length=200, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_failed', models.BooleanField(default=False)),
                ('delivery_failed_reason', models.CharField(max_length=100)),
                ('dropoff_address', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.ngoprofile')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donors.donors')),
                ('project_managers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_managers.projectmanager')),
            ],
            options={
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
