# Generated by Django 4.0.1 on 2022-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0006_ngodonations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodonations',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ngodonations',
            name='progress_report',
            field=models.FileField(blank=True, null=True, upload_to='beneficiaries/progress_report/'),
        ),
    ]
