# Generated by Django 4.0.1 on 2022-03-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_managers', '0003_projectmanager_email_confirmed'),
        ('NGO', '0007_ngodonations_accepted_ngodonations_progress_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='beneficiaries/progress_report/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.ngodonations')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_managers.projectmanager')),
            ],
        ),
        migrations.AlterField(
            model_name='ngodonations',
            name='progress_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.progressreports'),
        ),
    ]
