# Generated by Django 4.0.1 on 2022-03-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_managers', '0003_projectmanager_email_confirmed'),
        ('NGO', '0008_progressreports_alter_ngodonations_progress_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngodonations',
            name='progress_report',
        ),
        migrations.AddField(
            model_name='ngodonations',
            name='progress_report',
            field=models.ManyToManyField(to='NGO.ProgressReports'),
        ),
        migrations.RemoveField(
            model_name='progressreports',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='progressreports',
            name='project_manager',
            field=models.ManyToManyField(to='project_managers.ProjectManager'),
        ),
    ]
