# Generated by Django 4.0.1 on 2022-03-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_managers', '0003_projectmanager_email_confirmed'),
        ('NGO', '0009_remove_ngodonations_progress_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreports',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='progressreports',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_managers.projectmanager'),
        ),
    ]
