# Generated by Django 4.0.1 on 2022-03-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0010_remove_progressreports_project_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngodonations',
            name='progress_report',
        ),
        migrations.AddField(
            model_name='ngodonations',
            name='progress_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NGO.progressreports'),
        ),
    ]
