# Generated by Django 4.0.1 on 2022-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0011_remove_ngodonations_progress_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodonations',
            name='delivery_failed_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
