# Generated by Django 4.0.1 on 2022-03-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_ngo',
            field=models.BooleanField(default=False),
        ),
    ]
