# Generated by Django 4.0.1 on 2022-03-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmanager',
            options={'verbose_name_plural': 'Project Managers'},
        ),
    ]
